CREATE TABLE IF NOT EXISTS issue(
  tid INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  assigned_to VARCHAR(255) NOT NULL,
  assigned_by VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  PRIMARY KEY (tid)
)
